//
// Generated by JTB 1.3.2
//

package diamond.parser.syntaxtree;

/**
 * Grammar production: whereClause -> WhereClause() solutionModifier ->
 * SolutionModifier()
 */
@SuppressWarnings("serial")
public class Antecedent implements Node {

    public WhereClause whereClause;
    public SolutionModifier solutionModifier;

    public Antecedent(WhereClause n0, SolutionModifier n1) {
        whereClause = n0;
        solutionModifier = n1;
    }

    @Override
    public void accept(diamond.parser.visitor.Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(diamond.parser.visitor.GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(diamond.parser.visitor.GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(diamond.parser.visitor.GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}
