//
// Generated by JTB 1.3.2
//

package diamond.parser.syntaxtree;

/**
 * Grammar production: nodeToken -> <ASK> nodeListOptional -> ( DatasetClause()
 * )* whereClause -> WhereClause()
 */
@SuppressWarnings("serial")
public class AskQuery implements Node {

    public NodeToken nodeToken;
    public NodeListOptional nodeListOptional;
    public WhereClause whereClause;

    public AskQuery(NodeToken n0, NodeListOptional n1, WhereClause n2) {
        nodeToken = n0;
        nodeListOptional = n1;
        whereClause = n2;
    }

    public AskQuery(NodeListOptional n0, WhereClause n1) {
        nodeToken = new NodeToken("ask");
        nodeListOptional = n0;
        whereClause = n1;
    }

    @Override
    public void accept(diamond.parser.visitor.Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(diamond.parser.visitor.GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(diamond.parser.visitor.GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(diamond.parser.visitor.GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}
