//
// Generated by JTB 1.3.2
//

package diamond.parser.syntaxtree;

/**
 * Grammar production: nodeToken -> "[" propertyListNotEmpty ->
 * PropertyListNotEmpty() nodeToken1 -> "]"
 */
@SuppressWarnings("serial")
public class BlankNodePropertyList implements Node {

    public NodeToken nodeToken;
    public PropertyListNotEmpty propertyListNotEmpty;
    public NodeToken nodeToken1;

    public BlankNodePropertyList(NodeToken n0, PropertyListNotEmpty n1, NodeToken n2) {
        nodeToken = n0;
        propertyListNotEmpty = n1;
        nodeToken1 = n2;
    }

    public BlankNodePropertyList(PropertyListNotEmpty n0) {
        nodeToken = new NodeToken("[");
        propertyListNotEmpty = n0;
        nodeToken1 = new NodeToken("]");
    }

    @Override
    public void accept(diamond.parser.visitor.Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(diamond.parser.visitor.GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(diamond.parser.visitor.GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(diamond.parser.visitor.GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}
