//
// Generated by JTB 1.3.2
//

package diamond.parser.syntaxtree;

/**
 * Grammar production: conditionalAndExpression -> ConditionalAndExpression()
 * nodeListOptional -> ( "||" ConditionalAndExpression() )*
 */
@SuppressWarnings("serial")
public class ConditionalOrExpression implements Node {

    public ConditionalAndExpression conditionalAndExpression;
    public NodeListOptional nodeListOptional;

    public ConditionalOrExpression(ConditionalAndExpression n0, NodeListOptional n1) {
        conditionalAndExpression = n0;
        nodeListOptional = n1;
    }

    @Override
    public void accept(diamond.parser.visitor.Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(diamond.parser.visitor.GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(diamond.parser.visitor.GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(diamond.parser.visitor.GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}
