//
// Generated by JTB 1.3.2
//

package diamond.parser.syntaxtree;

/**
 * Grammar production: nodeToken -> <FROM> nodeChoice -> ( DefaultGraphClause()
 * | NamedGraphClause() )
 */
@SuppressWarnings("serial")
public class DatasetClause implements Node {

    public NodeToken nodeToken;
    public NodeChoice nodeChoice;

    public DatasetClause(NodeToken n0, NodeChoice n1) {
        nodeToken = n0;
        nodeChoice = n1;
    }

    public DatasetClause(NodeChoice n0) {
        nodeToken = new NodeToken("from");
        nodeChoice = n0;
    }

    @Override
    public void accept(diamond.parser.visitor.Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(diamond.parser.visitor.GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(diamond.parser.visitor.GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(diamond.parser.visitor.GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}
