//
// Generated by JTB 1.3.2
//

package diamond.parser.syntaxtree;

/**
 * Grammar production: nodeToken -> <FILTER> constraint -> Constraint()
 */
@SuppressWarnings("serial")
public class Filter implements Node {

    public NodeToken nodeToken;
    public Constraint constraint;

    public Filter(NodeToken n0, Constraint n1) {
        nodeToken = n0;
        constraint = n1;
    }

    public Filter(Constraint n0) {
        nodeToken = new NodeToken("filter");
        constraint = n0;
    }

    @Override
    public void accept(diamond.parser.visitor.Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(diamond.parser.visitor.GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(diamond.parser.visitor.GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(diamond.parser.visitor.GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}
