//
// Generated by JTB 1.3.2
//

package diamond.parser.syntaxtree;

/**
 * Grammar production: nodeToken -> <GRAPH> varOrIRIref -> VarOrIRIref()
 * groupGraphPattern -> GroupGraphPattern()
 */
@SuppressWarnings("serial")
public class GraphGraphPattern implements Node {

    public NodeToken nodeToken;
    public VarOrIRIref varOrIRIref;
    public GroupGraphPattern groupGraphPattern;

    public GraphGraphPattern(NodeToken n0, VarOrIRIref n1, GroupGraphPattern n2) {
        nodeToken = n0;
        varOrIRIref = n1;
        groupGraphPattern = n2;
    }

    public GraphGraphPattern(VarOrIRIref n0, GroupGraphPattern n1) {
        nodeToken = new NodeToken("graph");
        varOrIRIref = n0;
        groupGraphPattern = n1;
    }

    @Override
    public void accept(diamond.parser.visitor.Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(diamond.parser.visitor.GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(diamond.parser.visitor.GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(diamond.parser.visitor.GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}
