//
// Generated by JTB 1.3.2
//

package diamond.parser.syntaxtree;

/**
 * Grammar production: triplesSameSubject -> TriplesSameSubject() nodeOptional
 * -> ( "." ( InsertTriples() )? )?
 */
@SuppressWarnings("serial")
public class InsertTriples implements Node {

    public TriplesSameSubject triplesSameSubject;
    public NodeOptional nodeOptional;

    public InsertTriples(TriplesSameSubject n0, NodeOptional n1) {
        triplesSameSubject = n0;
        nodeOptional = n1;
    }

    @Override
    public void accept(diamond.parser.visitor.Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(diamond.parser.visitor.GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(diamond.parser.visitor.GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(diamond.parser.visitor.GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}
