//
// Generated by JTB 1.3.2
//

package diamond.parser.syntaxtree;

/**
 * Grammar production: iRIref -> IRIref() nodeOptional -> ( ArgList() )?
 */
@SuppressWarnings("serial")
public class IRIrefOrFunction implements Node {

    public IRIref iRIref;
    public NodeOptional nodeOptional;

    public IRIrefOrFunction(IRIref n0, NodeOptional n1) {
        iRIref = n0;
        nodeOptional = n1;
    }

    @Override
    public void accept(diamond.parser.visitor.Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(diamond.parser.visitor.GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(diamond.parser.visitor.GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(diamond.parser.visitor.GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}
