//
// Generated by JTB 1.3.2
//

package diamond.parser.syntaxtree;

/**
 * Grammar production: nodeToken -> <LIMIT> nodeToken1 -> <INTEGER>
 */
@SuppressWarnings("serial")
public class LimitClause implements Node {

    public NodeToken nodeToken;
    public NodeToken nodeToken1;

    public LimitClause(NodeToken n0, NodeToken n1) {
        nodeToken = n0;
        nodeToken1 = n1;
    }

    public LimitClause(NodeToken n0) {
        nodeToken = new NodeToken("limit");
        nodeToken1 = n0;
    }

    @Override
    public void accept(diamond.parser.visitor.Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(diamond.parser.visitor.GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(diamond.parser.visitor.GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(diamond.parser.visitor.GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}
