//
// Generated by JTB 1.3.2
//

package diamond.parser.syntaxtree;

/**
 * Grammar production: unaryExpression -> UnaryExpression() nodeListOptional ->
 * ( "*" UnaryExpression() | "/" UnaryExpression() )*
 */
@SuppressWarnings("serial")
public class MultiplicativeExpression implements Node {

    public UnaryExpression unaryExpression;
    public NodeListOptional nodeListOptional;

    public MultiplicativeExpression(UnaryExpression n0, NodeListOptional n1) {
        unaryExpression = n0;
        nodeListOptional = n1;
    }

    @Override
    public void accept(diamond.parser.visitor.Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(diamond.parser.visitor.GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(diamond.parser.visitor.GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(diamond.parser.visitor.GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}
