//
// Generated by JTB 1.3.2
//

package diamond.parser.syntaxtree;

/**
 * Grammar production: nodeToken -> <NAMED> sourceSelector -> SourceSelector()
 */
@SuppressWarnings("serial")
public class NamedGraphClause implements Node {

    public NodeToken nodeToken;
    public SourceSelector sourceSelector;

    public NamedGraphClause(NodeToken n0, SourceSelector n1) {
        nodeToken = n0;
        sourceSelector = n1;
    }

    public NamedGraphClause(SourceSelector n0) {
        nodeToken = new NodeToken("named");
        sourceSelector = n0;
    }

    @Override
    public void accept(diamond.parser.visitor.Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(diamond.parser.visitor.GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(diamond.parser.visitor.GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(diamond.parser.visitor.GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}
