//
// Generated by JTB 1.3.2
//

package diamond.parser.syntaxtree;

/**
 * The interface which all syntax tree classes must implement.
 */
public interface Node extends java.io.Serializable {

    public void accept(diamond.parser.visitor.Visitor v);

    public <R, A> R accept(diamond.parser.visitor.GJVisitor<R, A> v, A argu);

    public <R> R accept(diamond.parser.visitor.GJNoArguVisitor<R> v);

    public <A> void accept(diamond.parser.visitor.GJVoidVisitor<A> v, A argu);
}
