//
// Generated by JTB 1.3.2
//

package diamond.parser.syntaxtree;

/**
 * Represents a grammar choice, e.g. ( A | B )
 */
@SuppressWarnings("serial")
public class NodeChoice implements Node {

    public NodeChoice(Node node) {
        this(node, -1);
    }

    public NodeChoice(Node node, int whichChoice) {
        choice = node;
        which = whichChoice;
    }

    @Override
    public void accept(diamond.parser.visitor.Visitor v) {
        choice.accept(v);
    }

    @Override
    public <R, A> R accept(diamond.parser.visitor.GJVisitor<R, A> v, A argu) {
        return choice.accept(v, argu);
    }

    @Override
    public <R> R accept(diamond.parser.visitor.GJNoArguVisitor<R> v) {
        return choice.accept(v);
    }

    @Override
    public <A> void accept(diamond.parser.visitor.GJVoidVisitor<A> v, A argu) {
        choice.accept(v, argu);
    }

    public Node choice;
    public int which;
}
