//
// Generated by JTB 1.3.2
//

package diamond.parser.syntaxtree;

/**
 * The interface which NodeList, NodeListOptional, and NodeSequence implement.
 */
public interface NodeListInterface extends Node {

    public void addNode(Node n);

    public Node elementAt(int i);

    public java.util.Enumeration<Node> elements();

    public int size();

    @Override
    public void accept(diamond.parser.visitor.Visitor v);

    @Override
    public <R, A> R accept(diamond.parser.visitor.GJVisitor<R, A> v, A argu);

    @Override
    public <R> R accept(diamond.parser.visitor.GJNoArguVisitor<R> v);

    @Override
    public <A> void accept(diamond.parser.visitor.GJVoidVisitor<A> v, A argu);
}
