//
// Generated by JTB 1.3.2
//

package diamond.parser.syntaxtree;

/**
 * Grammar production: nodeToken -> <OPTIONAL> groupGraphPattern ->
 * GroupGraphPattern()
 */
@SuppressWarnings("serial")
public class OptionalGraphPattern implements Node {

    public NodeToken nodeToken;
    public GroupGraphPattern groupGraphPattern;

    public OptionalGraphPattern(NodeToken n0, GroupGraphPattern n1) {
        nodeToken = n0;
        groupGraphPattern = n1;
    }

    public OptionalGraphPattern(GroupGraphPattern n0) {
        nodeToken = new NodeToken("optional");
        groupGraphPattern = n0;
    }

    @Override
    public void accept(diamond.parser.visitor.Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(diamond.parser.visitor.GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(diamond.parser.visitor.GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(diamond.parser.visitor.GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}
