//
// Generated by JTB 1.3.2
//

package diamond.parser.syntaxtree;

/**
 * Grammar production: nodeToken -> <ORDER> nodeToken1 -> <BY> nodeList -> (
 * OrderCondition() )+
 */
@SuppressWarnings("serial")
public class OrderClause implements Node {

    public NodeToken nodeToken;
    public NodeToken nodeToken1;
    public NodeList nodeList;

    public OrderClause(NodeToken n0, NodeToken n1, NodeList n2) {
        nodeToken = n0;
        nodeToken1 = n1;
        nodeList = n2;
    }

    public OrderClause(NodeList n0) {
        nodeToken = new NodeToken("order");
        nodeToken1 = new NodeToken("by");
        nodeList = n0;
    }

    @Override
    public void accept(diamond.parser.visitor.Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(diamond.parser.visitor.GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(diamond.parser.visitor.GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(diamond.parser.visitor.GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}
