//
// Generated by JTB 1.3.2
//

package diamond.parser.syntaxtree;

/**
 * Grammar production: verb -> Verb() objectList -> ObjectList()
 * nodeListOptional -> ( ";" ( Verb() ObjectList() )? )*
 */
@SuppressWarnings("serial")
public class PropertyListNotEmpty implements Node {

    public Verb verb;
    public ObjectList objectList;
    public NodeListOptional nodeListOptional;

    public PropertyListNotEmpty(Verb n0, ObjectList n1, NodeListOptional n2) {
        verb = n0;
        objectList = n1;
        nodeListOptional = n2;
    }

    @Override
    public void accept(diamond.parser.visitor.Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(diamond.parser.visitor.GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(diamond.parser.visitor.GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(diamond.parser.visitor.GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}
