//
// Generated by JTB 1.3.2
//

package diamond.parser.syntaxtree;

/**
 * Grammar production: prologue -> Prologue() nodeChoice -> ( SelectQuery() |
 * ConstructQuery() | DescribeQuery() | AskQuery() )
 */
@SuppressWarnings("serial")
public class Query implements Node {

    public Prologue prologue;
    public NodeChoice nodeChoice;

    public Query(Prologue n0, NodeChoice n1) {
        prologue = n0;
        nodeChoice = n1;
    }

    @Override
    public void accept(diamond.parser.visitor.Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(diamond.parser.visitor.GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(diamond.parser.visitor.GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(diamond.parser.visitor.GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}
