//
// Generated by JTB 1.3.2
//

package diamond.parser.syntaxtree;

/**
 * Grammar production: numericExpression -> NumericExpression() nodeOptional ->
 * ( "=" NumericExpression() | "!=" NumericExpression() | "<"
 * NumericExpression() | ">" NumericExpression() | "<=" NumericExpression() |
 * ">=" NumericExpression() )?
 */
@SuppressWarnings("serial")
public class RelationalExpression implements Node {

    public NumericExpression numericExpression;
    public NodeOptional nodeOptional;

    public RelationalExpression(NumericExpression n0, NodeOptional n1) {
        numericExpression = n0;
        nodeOptional = n1;
    }

    @Override
    public void accept(diamond.parser.visitor.Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(diamond.parser.visitor.GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(diamond.parser.visitor.GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(diamond.parser.visitor.GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}
