//
// Generated by JTB 1.3.2
//

package diamond.parser.syntaxtree;

/**
 * Grammar production: nodeToken -> <DELETE> deleteClause -> DeleteClause()
 * nodeOptional -> ( <INSERT> InsertClause() )?
 */
@SuppressWarnings("serial")
public class RuleModifyClause implements Node {

    public NodeToken nodeToken;
    public DeleteClause deleteClause;
    public NodeOptional nodeOptional;

    public RuleModifyClause(NodeToken n0, DeleteClause n1, NodeOptional n2) {
        nodeToken = n0;
        deleteClause = n1;
        nodeOptional = n2;
    }

    public RuleModifyClause(DeleteClause n0, NodeOptional n1) {
        nodeToken = new NodeToken("delete");
        deleteClause = n0;
        nodeOptional = n1;
    }

    @Override
    public void accept(diamond.parser.visitor.Visitor v) {
        v.visit(this);
    }

    @Override
    public <R, A> R accept(diamond.parser.visitor.GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    @Override
    public <R> R accept(diamond.parser.visitor.GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    @Override
    public <A> void accept(diamond.parser.visitor.GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}
