select ?x ?y
where {
<http://dbpedia.org/resource/Tetris> <http://purl.org/dc/terms/subject> ?x.
?x <http://www.w3.org/2004/02/skos/core#broader> ?y.
?y <http://www.w3.org/2002/07/owl#sameAs> <http://dbpedia.org/resource/Category:NP-complete_problems>
}