# Test: 'xyz'@en = 'xyz'@EN
# $Id: lang-case-sensitivity-eq.rq,v 1.1 2013/01/15 14:12:34 carlosreyna Exp $

PREFIX     :    <http://example/>

SELECT *
{
    ?x1 :p ?v1 .
    ?x2 :p ?v2 .
    FILTER ( ?v1 = ?v2 )
}
