#Q6: Left Join
SELECT ?author
WHERE {
  ?x <http://www.example.org/type> <http://www.example.org/Book>;
     <http://www.example.org/author> ?author.
  OPTIONAL {
    ?y <http://www.example.org/type> <http://www.example.org/Article>;
       <http://www.example.org/author> ?author
  }
}
