//
// Generated by JTB 1.3.2
//

package diamond.parser.visitor;

import diamond.parser.syntaxtree.*;

/**
 * All void visitors must implement this interface.
 */

public interface Visitor {

    //
    // void Auto class visitors
    //

    public void visit(NodeList n);

    public void visit(NodeListOptional n);

    public void visit(NodeOptional n);

    public void visit(NodeSequence n);

    public void visit(NodeToken n);

    //
    // User-generated visitor methods below
    //

    /**
     * prologue -> Prologue() nodeChoice -> ( SelectQuery() | ConstructQuery() |
     * DescribeQuery() | AskQuery() )
     */
    public void visit(Query n);

    /**
     * nodeOptional -> ( BaseDecl() )? nodeListOptional -> ( PrefixDecl() )*
     */
    public void visit(Prologue n);

    /**
     * nodeToken -> <BASE> nodeToken1 -> <IRI_REF>
     */
    public void visit(BaseDecl n);

    /**
     * nodeToken -> <PREFIX> nodeToken1 -> <PNAME_NS> nodeToken2 -> <IRI_REF>
     */
    public void visit(PrefixDecl n);

    /**
     * nodeToken -> <SELECT> nodeOptional -> ( <DISTINCT> | <REDUCED> )?
     * nodeChoice -> ( ( Var() )+ | "*" ) nodeListOptional -> ( DatasetClause()
     * )* whereClause -> WhereClause() solutionModifier -> SolutionModifier()
     */
    public void visit(SelectQuery n);

    /**
     * nodeToken -> <CONSTRUCT> constructTemplate -> ConstructTemplate()
     * nodeListOptional -> ( DatasetClause() )* whereClause -> WhereClause()
     * solutionModifier -> SolutionModifier()
     */
    public void visit(ConstructQuery n);

    /**
     * nodeToken -> <DESCRIBE> nodeChoice -> ( ( VarOrIRIref() )+ | "*" )
     * nodeListOptional -> ( DatasetClause() )* nodeOptional -> ( WhereClause()
     * )? solutionModifier -> SolutionModifier()
     */
    public void visit(DescribeQuery n);

    /**
     * nodeToken -> <ASK> nodeListOptional -> ( DatasetClause() )* whereClause
     * -> WhereClause()
     */
    public void visit(AskQuery n);

    /**
     * nodeToken -> <FROM> nodeChoice -> ( DefaultGraphClause() |
     * NamedGraphClause() )
     */
    public void visit(DatasetClause n);

    /**
     * sourceSelector -> SourceSelector()
     */
    public void visit(DefaultGraphClause n);

    /**
     * nodeToken -> <NAMED> sourceSelector -> SourceSelector()
     */
    public void visit(NamedGraphClause n);

    /**
     * iRIref -> IRIref()
     */
    public void visit(SourceSelector n);

    /**
     * nodeOptional -> ( <WHERE> )? groupGraphPattern -> GroupGraphPattern()
     */
    public void visit(WhereClause n);

    /**
     * nodeOptional -> ( OrderClause() )? nodeOptional1 -> (
     * LimitOffsetClauses() )?
     */
    public void visit(SolutionModifier n);

    /**
     * nodeChoice -> ( LimitClause() ( OffsetClause() )? | OffsetClause() (
     * LimitClause() )? )
     */
    public void visit(LimitOffsetClauses n);

    /**
     * nodeToken -> <ORDER> nodeToken1 -> <BY> nodeList -> ( OrderCondition() )+
     */
    public void visit(OrderClause n);

    /**
     * nodeChoice -> ( ( <ASC> | <DESC> ) BrackettedExpression() ) | (
     * Constraint() | Var() )
     */
    public void visit(OrderCondition n);

    /**
     * nodeToken -> <LIMIT> nodeToken1 -> <INTEGER>
     */
    public void visit(LimitClause n);

    /**
     * nodeToken -> <OFFSET> nodeToken1 -> <INTEGER>
     */
    public void visit(OffsetClause n);

    /**
     * nodeToken -> "{" nodeOptional -> ( TriplesBlock() )? nodeListOptional ->
     * ( GraphPatternNotTriples() ( "." )? ( TriplesBlock() )? )* nodeToken1 ->
     * "}"
     */
    public void visit(GroupGraphPattern n);

    /**
     * triplesSameSubject -> TriplesSameSubject() nodeOptional -> ( "." (
     * TriplesBlock() )? )?
     */
    public void visit(TriplesBlock n);

    /**
     * nodeChoice -> OptionalGraphPattern() | GroupOrUnionGraphPattern() |
     * GraphGraphPattern() | Filter() | Bind()
     */
    public void visit(GraphPatternNotTriples n);

    /**
     * nodeToken -> <OPTIONAL> groupGraphPattern -> GroupGraphPattern()
     */
    public void visit(OptionalGraphPattern n);

    /**
     * nodeToken -> <GRAPH> varOrIRIref -> VarOrIRIref() groupGraphPattern ->
     * GroupGraphPattern()
     */
    public void visit(GraphGraphPattern n);

    /**
     * groupGraphPattern -> GroupGraphPattern() nodeListOptional -> ( <UNION>
     * GroupGraphPattern() )*
     */
    public void visit(GroupOrUnionGraphPattern n);

    /**
     * nodeToken -> <FILTER> constraint -> Constraint()
     */
    public void visit(Filter n);

    /**
     * nodeChoice -> BrackettedExpression() | BuiltInCall() | FunctionCall()
     */
    public void visit(Constraint n);

    /**
     * iRIref -> IRIref() argList -> ArgList()
     */
    public void visit(FunctionCall n);

    /**
     * nodeChoice -> ( <NIL> | "(" Expression() ( "," Expression() )* ")" )
     */
    public void visit(ArgList n);

    /**
     * nodeToken -> "{" nodeOptional -> ( ConstructTriples() )? nodeToken1 ->
     * "}"
     */
    public void visit(ConstructTemplate n);

    /**
     * triplesSameSubject -> TriplesSameSubject() nodeOptional -> ( "." (
     * ConstructTriples() )? )?
     */
    public void visit(ConstructTriples n);

    /**
     * nodeChoice -> VarOrTerm() PropertyListNotEmpty() | TriplesNode()
     * PropertyList()
     */
    public void visit(TriplesSameSubject n);

    /**
     * verb -> Verb() objectList -> ObjectList() nodeListOptional -> ( ";" (
     * Verb() ObjectList() )? )*
     */
    public void visit(PropertyListNotEmpty n);

    /**
     * nodeOptional -> ( PropertyListNotEmpty() )?
     */
    public void visit(PropertyList n);

    /**
     * sparqlObject -> SparqlObject() nodeListOptional -> ( "," SparqlObject()
     * )*
     */
    public void visit(ObjectList n);

    /**
     * graphNode -> GraphNode()
     */
    public void visit(SparqlObject n);

    /**
     * nodeChoice -> VarOrIRIref() | <TYPE_A> | PutativeLiteral()
     */
    public void visit(Verb n);

    /**
     * nodeChoice -> SparqlCollection() | BlankNodePropertyList()
     */
    public void visit(TriplesNode n);

    /**
     * nodeToken -> "[" propertyListNotEmpty -> PropertyListNotEmpty()
     * nodeToken1 -> "]"
     */
    public void visit(BlankNodePropertyList n);

    /**
     * nodeToken -> "(" nodeList -> ( GraphNode() )+ nodeToken1 -> ")"
     */
    public void visit(SparqlCollection n);

    /**
     * nodeChoice -> VarOrTerm() | TriplesNode()
     */
    public void visit(GraphNode n);

    /**
     * nodeChoice -> Var() | GraphTerm()
     */
    public void visit(VarOrTerm n);

    /**
     * nodeChoice -> Var() | IRIref()
     */
    public void visit(VarOrIRIref n);

    /**
     * nodeChoice -> <VAR1> | <VAR2>
     */
    public void visit(Var n);

    /**
     * nodeChoice -> IRIref() | RDFLiteral() | NumericLiteral() |
     * BooleanLiteral() | BlankNode() | PutativeLiteral() | <NIL>
     */
    public void visit(GraphTerm n);

    /**
     * conditionalOrExpression -> ConditionalOrExpression()
     */
    public void visit(Expression n);

    /**
     * conditionalAndExpression -> ConditionalAndExpression() nodeListOptional
     * -> ( "||" ConditionalAndExpression() )*
     */
    public void visit(ConditionalOrExpression n);

    /**
     * valueLogical -> ValueLogical() nodeListOptional -> ( "&&" ValueLogical()
     * )*
     */
    public void visit(ConditionalAndExpression n);

    /**
     * relationalExpression -> RelationalExpression()
     */
    public void visit(ValueLogical n);

/**
     * numericExpression -> NumericExpression() nodeOptional -> ( "="
     * NumericExpression() | "!=" NumericExpression() | "<" NumericExpression()
     * | ">" NumericExpression() | "<=" NumericExpression() | ">="
     * NumericExpression() )?
     */
    public void visit(RelationalExpression n);

    /**
     * additiveExpression -> AdditiveExpression()
     */
    public void visit(NumericExpression n);

    /**
     * multiplicativeExpression -> MultiplicativeExpression() nodeListOptional
     * -> ( "+" MultiplicativeExpression() | "-" MultiplicativeExpression() |
     * NumericLiteralPositive() | NumericLiteralNegative() )*
     */
    public void visit(AdditiveExpression n);

    /**
     * unaryExpression -> UnaryExpression() nodeListOptional -> ( "*"
     * UnaryExpression() | "/" UnaryExpression() )*
     */
    public void visit(MultiplicativeExpression n);

    /**
     * nodeChoice -> ( "!" PrimaryExpression() | "+" PrimaryExpression() | "-"
     * PrimaryExpression() | PrimaryExpression() )
     */
    public void visit(UnaryExpression n);

    /**
     * nodeChoice -> BrackettedExpression() | BuiltInCall() | IRIrefOrFunction()
     * | RDFLiteral() | NumericLiteral() | BooleanLiteral() | Var()
     */
    public void visit(PrimaryExpression n);

    /**
     * nodeToken -> "(" expression -> Expression() nodeToken1 -> ")"
     */
    public void visit(BrackettedExpression n);

    /**
     * nodeChoice -> ( <STR> "(" Expression() ")" | <LANG> "(" Expression() ")"
     * | <LANGMATCHES> "(" Expression() "," Expression() ")" | <DATATYPE> "("
     * Expression() ")" | <BOUND> "(" Var() ")" | <SAME_TERM> "(" Expression()
     * "," Expression() ")" | <IS_IRI> "(" Expression() ")" | <IS_URI> "("
     * Expression() ")" | <IS_BLANK> "(" Expression() ")" | <IS_LITERAL> "("
     * Expression() ")" | RegexExpression() )
     */
    public void visit(BuiltInCall n);

    /**
     * nodeToken -> <REGEX> nodeToken1 -> "(" expression -> Expression()
     * nodeToken2 -> "," expression1 -> Expression() nodeOptional -> ( ","
     * Expression() )? nodeToken3 -> ")"
     */
    public void visit(RegexExpression n);

    /**
     * iRIref -> IRIref() nodeOptional -> ( ArgList() )?
     */
    public void visit(IRIrefOrFunction n);

    /**
     * sparqlString -> SparqlString() nodeOptional -> ( <LANGTAG> | ( "^^"
     * IRIref() ) )?
     */
    public void visit(RDFLiteral n);

    /**
     * nodeChoice -> ( NumericLiteralUnsigned() | NumericLiteralPositive() |
     * NumericLiteralNegative() )
     */
    public void visit(NumericLiteral n);

    /**
     * nodeChoice -> <INTEGER> | <DECIMAL> | <DOUBLE>
     */
    public void visit(NumericLiteralUnsigned n);

    /**
     * nodeChoice -> <INTEGER_POSITIVE> | <DECIMAL_POSITIVE> | <DOUBLE_POSITIVE>
     */
    public void visit(NumericLiteralPositive n);

    /**
     * nodeChoice -> <INTEGER_NEGATIVE> | <DECIMAL_NEGATIVE> | <DOUBLE_NEGATIVE>
     */
    public void visit(NumericLiteralNegative n);

    /**
     * nodeChoice -> <TRUE> | <FALSE>
     */
    public void visit(BooleanLiteral n);

    /**
     * nodeChoice -> <STRING_LITERAL1> | <STRING_LITERAL2> |
     * <STRING_LITERAL_LONG1> | <STRING_LITERAL_LONG2>
     */
    public void visit(SparqlString n);

    /**
     * nodeChoice -> <IRI_REF> | PrefixedName()
     */
    public void visit(IRIref n);

    /**
     * nodeChoice -> <PNAME_LN> | <PNAME_NS>
     */
    public void visit(PrefixedName n);

    /**
     * nodeChoice -> <BLANK_NODE_LABEL> | <ANON>
     */
    public void visit(BlankNode n);

    /**
     * nodeToken -> <PUTATIVE_LITERAL>
     */
    public void visit(PutativeLiteral n);

    /**
     * prologue -> Prologue() nodeList -> ( "[" Rule() "]" )+
     */
    public void visit(SparqlSpin n);

    /**
     * consequent -> Consequent() nodeToken -> <WHERE> antecedent ->
     * Antecedent()
     */
    public void visit(Rule n);

    /**
     * nodeChoice -> RuleConstructClause() | RuleModifyClause()
     */
    public void visit(Consequent n);

    /**
     * nodeToken -> <CONSTRUCT> constructTemplate -> ConstructTemplate()
     * nodeListOptional -> ( DatasetClause() )*
     */
    public void visit(RuleConstructClause n);

    /**
     * nodeToken -> <DELETE> deleteClause -> DeleteClause() nodeOptional -> (
     * <INSERT> InsertClause() )?
     */
    public void visit(RuleModifyClause n);

    /**
     * nodeToken -> "{" nodeOptional -> ( DeleteTriples() )? nodeToken1 -> "}"
     */
    public void visit(DeleteClause n);

    /**
     * triplesSameSubject -> TriplesSameSubject() nodeOptional -> ( "." (
     * DeleteTriples() )? )?
     */
    public void visit(DeleteTriples n);

    /**
     * nodeToken -> "{" nodeOptional -> ( InsertTriples() )? nodeToken1 -> "}"
     */
    public void visit(InsertClause n);

    /**
     * triplesSameSubject -> TriplesSameSubject() nodeOptional -> ( "." (
     * InsertTriples() )? )?
     */
    public void visit(InsertTriples n);

    /**
     * whereClause -> WhereClause() solutionModifier -> SolutionModifier()
     */
    public void visit(Antecedent n);

    /**
     * nodeToken -> <BIND> nodeToken1 -> "(" expression -> Expression()
     * nodeToken2 -> <AS> var -> Var() nodeToken3 -> ")"
     */
    public void visit(Bind n);

}
