# $Id: syn-blabel-cross-graph-bad.rq,v 1.1 2013/01/15 14:12:36 carlosreyna Exp $
# BNode label used across a GRAPH.
PREFIX : <http://xmlns.com/foaf/0.1/>

ASK { _:who :homepage ?homepage 
      GRAPH ?g { ?someone :made ?homepage } 
      _:who :schoolHomepage ?schoolPage }
